[[module.imports]]
path = "github.com/hbstack/docs"

[[module.imports]]
path = "github.com/hugomods/decap-cms"

[params.decap_cms._configs.hb_docs_doc]
name = "documents"
label = "Documents"
label_singular = "Document"
create = true
_extends = [
  "field_title",
  "field_link_title",
  "field_draft",
  "hb_field_featured",
  "hb_field_pinned",
  "field_date",
  "field_description",
  "field_images",
  "field_aliases",
  "field_authors",
  "field_series",
  "field_categories",
  "field_tags",
  "field_body"
]
[params.decap_cms._configs.hb_docs_doc.fields.nav_weight]
i18n = "duplicate"
name = "nav_weight"
label = "Navigation Weight"
widget = "number"
