[params.hugopress.modules.hb-docs-toc-scrollspy.attributes.hb-docs-doc-content]
cacheable = true

[[module.imports]]
path = "github.com/hbstack/toc-scrollspy"

[[module.imports]]
path = "github.com/hbstack/docs"
