on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-modules

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          config-file: release-please-modules-config.json
